// <auto-generated />
using System;
using Klavelvet.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klavelvet.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230318144219_FeaturedProducts")]
    partial class FeaturedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Klavelvet.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Name = "Corsets",
                            Url = "corsets"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Name = "Dresses",
                            Url = "dresses"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Name = "Accesories",
                            Url = "accesories"
                        });
                });

            modelBuilder.Entity("Klavelvet.Shared.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1da89c8-9d11-4808-aec3-e25a3117d29c"),
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in massa purus. Fusce eleifend ullamcorper diam, vel dictum velit auctor vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ultrices dolor sit amet lorem posuere, eget rhoncus ipsum euismod.",
                            Featured = true,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/0/01/Corset1878taille46_300gram.png",
                            Title = "Lorem ipsum corset 1"
                        },
                        new
                        {
                            Id = new Guid("fec703b8-d206-408f-ade9-0b0c338ea98b"),
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique auctor nibh vel venenatis. Praesent consequat, erat vitae venenatis volutpat, justo dolor imperdiet ipsum, vel euismod mi odio a dolor. Donec iaculis, ante ac tempor accumsan, urna nisi lacinia justo, sed lobortis orci odio ac augue.",
                            Featured = false,
                            ImageURL = "/images/products/71vhl6wsxcl._ac_ul400_.jpg",
                            Title = "Lorem ipsum corset 2"
                        },
                        new
                        {
                            Id = new Guid("7d5a1144-d392-49d5-be2e-d926f553901f"),
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in massa purus. Fusce eleifend ullamcorper diam, vel dictum velit auctor vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ultrices dolor sit amet lorem posuere, eget rhoncus ipsum euismod.",
                            Featured = false,
                            ImageURL = "/images/products/61+xvxreiyl._ac_ul1001_.jpg",
                            Title = "Lorem ipsum corset 3"
                        },
                        new
                        {
                            Id = new Guid("6a063e94-37a5-4019-be3d-664dd453afa9"),
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique auctor nibh vel venenatis. Praesent consequat, erat vitae venenatis volutpat, justo dolor imperdiet ipsum, vel euismod mi odio a dolor. Donec iaculis, ante ac tempor accumsan, urna nisi lacinia justo, sed lobortis orci odio ac augue.",
                            Featured = false,
                            ImageURL = "/images/products/no-photo-placeholder.png",
                            Title = "Lorem ipsum corset 4"
                        },
                        new
                        {
                            Id = new Guid("9fd60b55-ab68-46bb-a683-9dcf766c5612"),
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in massa purus. Fusce eleifend ullamcorper diam, vel dictum velit auctor vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ultrices dolor sit amet lorem posuere, eget rhoncus ipsum euismod.",
                            Featured = true,
                            ImageURL = "/images/products/dresses/dress_1.jpg",
                            Title = "Lorem ipsum dress 1"
                        },
                        new
                        {
                            Id = new Guid("d9433ebc-3715-4157-8edc-25e3502527e2"),
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique auctor nibh vel venenatis. Praesent consequat, erat vitae venenatis volutpat, justo dolor imperdiet ipsum, vel euismod mi odio a dolor. Donec iaculis, ante ac tempor accumsan, urna nisi lacinia justo, sed lobortis orci odio ac augue.",
                            Featured = false,
                            ImageURL = "/images/products/dresses/dress_2.jpg",
                            Title = "Lorem ipsum dress 2"
                        },
                        new
                        {
                            Id = new Guid("df5b6339-e65b-488f-b837-b7434445ce54"),
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in massa purus. Fusce eleifend ullamcorper diam, vel dictum velit auctor vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ultrices dolor sit amet lorem posuere, eget rhoncus ipsum euismod.",
                            Featured = false,
                            ImageURL = "/images/products/dresses/dress_3.jpg",
                            Title = "Lorem ipsum dress 3"
                        },
                        new
                        {
                            Id = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique auctor nibh vel venenatis. Praesent consequat, erat vitae venenatis volutpat, justo dolor imperdiet ipsum, vel euismod mi odio a dolor. Donec iaculis, ante ac tempor accumsan, urna nisi lacinia justo, sed lobortis orci odio ac augue.",
                            Featured = false,
                            ImageURL = "/images/products/dresses/dress_4.jpg",
                            Title = "Lorem ipsum dress 4"
                        },
                        new
                        {
                            Id = new Guid("5cc1a1e7-8f22-42cd-b62e-22ddb1554772"),
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in massa purus. Fusce eleifend ullamcorper diam, vel dictum velit auctor vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ultrices dolor sit amet lorem posuere, eget rhoncus ipsum euismod.",
                            Featured = true,
                            ImageURL = "/images/products/accesories/bracelet_1.png",
                            Title = "Lorem ipsum bracelet 1"
                        },
                        new
                        {
                            Id = new Guid("640f3165-8940-4768-82c9-9629873cb1a9"),
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique auctor nibh vel venenatis. Praesent consequat, erat vitae venenatis volutpat, justo dolor imperdiet ipsum, vel euismod mi odio a dolor. Donec iaculis, ante ac tempor accumsan, urna nisi lacinia justo, sed lobortis orci odio ac augue.",
                            Featured = false,
                            ImageURL = "/images/products/no-photo-placeholder.png",
                            Title = "Lorem ipsum bracelet 2"
                        },
                        new
                        {
                            Id = new Guid("843b31fa-e860-4ca9-9b74-42cff6ac4bc7"),
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in massa purus. Fusce eleifend ullamcorper diam, vel dictum velit auctor vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ultrices dolor sit amet lorem posuere, eget rhoncus ipsum euismod.",
                            Featured = false,
                            ImageURL = "/images/products/no-photo-placeholder.png",
                            Title = "Lorem ipsum bracelet 3"
                        },
                        new
                        {
                            Id = new Guid("3b9b19a7-3d59-499c-8d1b-94fa1b1cf8a8"),
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique auctor nibh vel venenatis. Praesent consequat, erat vitae venenatis volutpat, justo dolor imperdiet ipsum, vel euismod mi odio a dolor. Donec iaculis, ante ac tempor accumsan, urna nisi lacinia justo, sed lobortis orci odio ac augue.",
                            Featured = false,
                            ImageURL = "/images/products/no-photo-placeholder.png",
                            Title = "Lorem ipsum bracelet 4"
                        });
                });

            modelBuilder.Entity("Klavelvet.Shared.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unique Size"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Size XS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Size S"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Size M"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Size L"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Size XL"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Size XXL"
                        });
                });

            modelBuilder.Entity("Klavelvet.Shared.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("fec703b8-d206-408f-ade9-0b0c338ea98b"),
                            ProductTypeId = 2,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("fec703b8-d206-408f-ade9-0b0c338ea98b"),
                            ProductTypeId = 3,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("fec703b8-d206-408f-ade9-0b0c338ea98b"),
                            ProductTypeId = 4,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("fec703b8-d206-408f-ade9-0b0c338ea98b"),
                            ProductTypeId = 5,
                            OriginalPrice = 59.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = new Guid("fec703b8-d206-408f-ade9-0b0c338ea98b"),
                            ProductTypeId = 6,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("7d5a1144-d392-49d5-be2e-d926f553901f"),
                            ProductTypeId = 2,
                            OriginalPrice = 59.99m,
                            Price = 59.99m
                        },
                        new
                        {
                            ProductId = new Guid("7d5a1144-d392-49d5-be2e-d926f553901f"),
                            ProductTypeId = 4,
                            OriginalPrice = 59.99m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = new Guid("7d5a1144-d392-49d5-be2e-d926f553901f"),
                            ProductTypeId = 5,
                            OriginalPrice = 59.99m,
                            Price = 59.99m
                        },
                        new
                        {
                            ProductId = new Guid("7d5a1144-d392-49d5-be2e-d926f553901f"),
                            ProductTypeId = 6,
                            OriginalPrice = 59.99m,
                            Price = 59.99m
                        },
                        new
                        {
                            ProductId = new Guid("5cc1a1e7-8f22-42cd-b62e-22ddb1554772"),
                            ProductTypeId = 1,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("d9433ebc-3715-4157-8edc-25e3502527e2"),
                            ProductTypeId = 2,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("d9433ebc-3715-4157-8edc-25e3502527e2"),
                            ProductTypeId = 3,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("d9433ebc-3715-4157-8edc-25e3502527e2"),
                            ProductTypeId = 4,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("d9433ebc-3715-4157-8edc-25e3502527e2"),
                            ProductTypeId = 5,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("843b31fa-e860-4ca9-9b74-42cff6ac4bc7"),
                            ProductTypeId = 1,
                            OriginalPrice = 29.99m,
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = new Guid("6a063e94-37a5-4019-be3d-664dd453afa9"),
                            ProductTypeId = 3,
                            OriginalPrice = 49.99m,
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = new Guid("6a063e94-37a5-4019-be3d-664dd453afa9"),
                            ProductTypeId = 4,
                            OriginalPrice = 49.99m,
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = new Guid("6a063e94-37a5-4019-be3d-664dd453afa9"),
                            ProductTypeId = 5,
                            OriginalPrice = 49.99m,
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = new Guid("3b9b19a7-3d59-499c-8d1b-94fa1b1cf8a8"),
                            ProductTypeId = 1,
                            OriginalPrice = 39.99m,
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = new Guid("640f3165-8940-4768-82c9-9629873cb1a9"),
                            ProductTypeId = 1,
                            OriginalPrice = 39.99m,
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = new Guid("9fd60b55-ab68-46bb-a683-9dcf766c5612"),
                            ProductTypeId = 2,
                            OriginalPrice = 69.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("9fd60b55-ab68-46bb-a683-9dcf766c5612"),
                            ProductTypeId = 3,
                            OriginalPrice = 69.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("9fd60b55-ab68-46bb-a683-9dcf766c5612"),
                            ProductTypeId = 4,
                            OriginalPrice = 69.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("9fd60b55-ab68-46bb-a683-9dcf766c5612"),
                            ProductTypeId = 5,
                            OriginalPrice = 79.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("9fd60b55-ab68-46bb-a683-9dcf766c5612"),
                            ProductTypeId = 6,
                            OriginalPrice = 79.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("df5b6339-e65b-488f-b837-b7434445ce54"),
                            ProductTypeId = 3,
                            OriginalPrice = 79.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("df5b6339-e65b-488f-b837-b7434445ce54"),
                            ProductTypeId = 6,
                            OriginalPrice = 79.99m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = new Guid("a1da89c8-9d11-4808-aec3-e25a3117d29c"),
                            ProductTypeId = 3,
                            OriginalPrice = 79.99m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = new Guid("a1da89c8-9d11-4808-aec3-e25a3117d29c"),
                            ProductTypeId = 4,
                            OriginalPrice = 79.99m,
                            Price = 89.99m
                        },
                        new
                        {
                            ProductId = new Guid("a1da89c8-9d11-4808-aec3-e25a3117d29c"),
                            ProductTypeId = 5,
                            OriginalPrice = 79.99m,
                            Price = 89.99m
                        },
                        new
                        {
                            ProductId = new Guid("a1da89c8-9d11-4808-aec3-e25a3117d29c"),
                            ProductTypeId = 6,
                            OriginalPrice = 79.99m,
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = new Guid("a1da89c8-9d11-4808-aec3-e25a3117d29c"),
                            ProductTypeId = 7,
                            OriginalPrice = 79.99m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            ProductTypeId = 2,
                            OriginalPrice = 79.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            ProductTypeId = 3,
                            OriginalPrice = 79.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            ProductTypeId = 4,
                            OriginalPrice = 79.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            ProductTypeId = 5,
                            OriginalPrice = 79.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            ProductTypeId = 6,
                            OriginalPrice = 79.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("9a9f0aca-829a-49ba-834f-fb7c67bb3f14"),
                            ProductTypeId = 7,
                            OriginalPrice = 79.99m,
                            Price = 49.99m
                        });
                });

            modelBuilder.Entity("Klavelvet.Shared.Models.Product", b =>
                {
                    b.HasOne("Klavelvet.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Klavelvet.Shared.Models.ProductVariant", b =>
                {
                    b.HasOne("Klavelvet.Shared.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klavelvet.Shared.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Klavelvet.Shared.Models.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
